# Generated by Django 5.0.2 on 2024-09-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_author_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='captions',
            field=models.ManyToManyField(blank=True, null=True, to='blog.tag', verbose_name='blogs'),
        ),
    ]
