# Generated by Django 5.0.2 on 2024-09-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_captions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blogTitle',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='post',
            name='captions',
            field=models.ManyToManyField(blank=True, null=True, to='blog.tag', verbose_name='captions'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imageName',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='tag',
            name='caption',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
