# Generated by Django 5.0.2 on 2024-09-25 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_blogtitle_alter_post_captions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='captions',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='captions'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=70)),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='post')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comments', verbose_name='reply')),
            ],
        ),
    ]
